# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_notice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='When the Notice was created.'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Last update date'),
        ),
    ]
