# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20180123_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='excerpt',
            field=models.CharField(blank=True, help_text='An excerpt to be used for the front page.', max_length=400, null=True),
        ),
    ]
