#
# Dockerfile for the ifx.rc portal application
#
# Use a volume to deploy code to /app

FROM python:3.6

EXPOSE 80
RUN apt-get update -y && apt-get install -y \
    git \
    gcc \
    procps \
    vim \
    nginx \
    supervisor


WORKDIR /app

ADD requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && \
    pip install gunicorn && \
    pip install git+https://github.com/harvardinformatics/ifxurls.git && \
    pip install git+https://github.com/harvardinformatics/ifxauth.git && \
    pip install git+https://github.com/harvardinformatics/ifxuser.git && \
    pip install -r requirements.txt

RUN echo "daemon off;" >> /etc/nginx/nginx.conf
COPY etc/nginx-dev.conf /etc/nginx/sites-available/default
COPY etc/htpasswd   /etc/nginx/htpasswd
COPY etc/supervisor.conf /etc/supervisor/conf.d/app.conf
ENV DJANGO_SETTINGS_FILE=settings

ENV PYTHONPATH=/app

# Set Django setting DEBUG to True
ENV DJANGO_DEBUG=TRUE
ENV DJANGO_LOGLEVEL=DEBUG

CMD ["/usr/bin/supervisord","-n"]
